/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package appli_pro;

import com.mysql.jdbc.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.DiscriminatorType;
import javax.swing.JOptionPane;

/**
 *
 * @author nc
 */
public class InterfaceGraphique extends javax.swing.JFrame {

    /**
     * attribut qui indique si l'etudiant est connecté ou non
     */
    private boolean connecte;
//    private Directeur infoDirecteur;

    /**
     * interface graphique
     */
    private Connexion fenConnexion;
    private Deconnexion fenDeconnexion;
//    private Inscription fenInscription;

    /**
     * constructeur : Creates new form InterfaceGraphique
     *
     */
    public InterfaceGraphique() {
        initComponents();
        //par defaut, la connexion est inactive
        this.connecte = false;
        //element du menu de deconnexion grisé
        this.majConnexion();
        //centrage
        this.setLocationRelativeTo(null);
        //titre 
        this.setTitle("Gestion Entreprise GSBV");

        jTabbedMenuDirecteur.setVisible(false);
        jPanelMenuResponsable.setVisible(false);
        jPanelMenuEmploye.setVisible(false);
        jPanelMenuAccueil.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        desktopPane = new javax.swing.JDesktopPane();
        jTabbedMenuDirecteur = new javax.swing.JTabbedPane();
        jPanelEmbaucher = new javax.swing.JPanel();
        jTextFieldNomEmbauche = new javax.swing.JTextField();
        jTextFieldPrenomEmbauche = new javax.swing.JTextField();
        jTextFieldAdresseRueEmbauche = new javax.swing.JTextField();
        jTextFieldEmailEmbauche = new javax.swing.JTextField();
        jTextFieldNumTelPersoEmbauche = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldAdresseCpEmbauche = new javax.swing.JTextField();
        jTextFieldAdresseVilleEmbauche = new javax.swing.JTextField();
        jTextFieldNumTelProEmbauche = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldIdEmbauche = new javax.swing.JTextField();
        jTextFieldMDPEmbauche = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jPanelPromouvoir = new javax.swing.JPanel();
        jButtonProm = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListEmploye = new javax.swing.JList<>();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldNomProm = new javax.swing.JTextField();
        jTextFieldPrenomProm = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanelMenuResponsable = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jPanelMenuAccueil = new javax.swing.JPanel();
        jButtonConnexion = new javax.swing.JButton();
        jButtonInscription = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanelMenuEmploye = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButtonModif = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        nomMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        connexionMenuItem = new javax.swing.JMenuItem();
        deconnexionMenuItem = new javax.swing.JMenuItem();
        SortieMenuItem = new javax.swing.JMenuItem();
        aideMenu = new javax.swing.JMenu();
        aproposMenuItem = new javax.swing.JMenuItem();
        nomjMenu = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenu5.setText("jMenu5");

        jMenu6.setText("jMenu6");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBorder(new javax.swing.border.MatteBorder(null));

        jButton2.setText("Embaucher");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Annuler");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel7.setText("Nom");

        jLabel8.setText("Prénom");

        jLabel9.setText("Téléphone");

        jLabel10.setText("Adresse");

        jLabel12.setText("E-mail");

        jLabel2.setText("Perso:");

        jLabel3.setText("Pro:");

        jLabel4.setText("Identifiant");

        jLabel5.setText("Mdp");

        jLabel13.setText("Embauchez un nouvel employé");

        jLabel30.setText("Coordonnées : ");

        jLabel31.setText("Identité :");

        jLabel32.setText("Compte :");

        org.jdesktop.layout.GroupLayout jPanelEmbaucherLayout = new org.jdesktop.layout.GroupLayout(jPanelEmbaucher);
        jPanelEmbaucher.setLayout(jPanelEmbaucherLayout);
        jPanelEmbaucherLayout.setHorizontalGroup(
            jPanelEmbaucherLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelEmbaucherLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelEmbaucherLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelEmbaucherLayout.createSequentialGroup()
                        .add(jPanelEmbaucherLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanelEmbaucherLayout.createSequentialGroup()
                                .add(jLabel31)
                                .add(301, 301, 301)
                                .add(jButton3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 102, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanelEmbaucherLayout.createSequentialGroup()
                                .add(jLabel32)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jSeparator5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 695, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanelEmbaucherLayout.createSequentialGroup()
                                .add(jLabel30)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jSeparator4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 674, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanelEmbaucherLayout.createSequentialGroup()
                                .add(jPanelEmbaucherLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jPanelEmbaucherLayout.createSequentialGroup()
                                        .add(jLabel9)
                                        .add(18, 18, 18)
                                        .add(jLabel2))
                                    .add(jLabel12))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jPanelEmbaucherLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jTextFieldEmailEmbauche, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 160, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jPanelEmbaucherLayout.createSequentialGroup()
                                        .add(jPanelEmbaucherLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jTextFieldAdresseRueEmbauche, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 134, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(jPanelEmbaucherLayout.createSequentialGroup()
                                                .add(jTextFieldNumTelPersoEmbauche, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 108, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                                .add(jLabel3)))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(jPanelEmbaucherLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jTextFieldNumTelProEmbauche, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 105, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(jPanelEmbaucherLayout.createSequentialGroup()
                                                .add(jTextFieldAdresseCpEmbauche, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                                .add(jTextFieldAdresseVilleEmbauche, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))))
                            .add(jPanelEmbaucherLayout.createSequentialGroup()
                                .add(jLabel4)
                                .add(50, 50, 50)
                                .add(jPanelEmbaucherLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jTextFieldMDPEmbauche, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 106, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jTextFieldIdEmbauche, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 106, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                .add(108, 108, 108)
                                .add(jButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 139, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(0, 0, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelEmbaucherLayout.createSequentialGroup()
                        .add(0, 0, Short.MAX_VALUE)
                        .add(jLabel8)
                        .add(787, 787, 787))
                    .add(jPanelEmbaucherLayout.createSequentialGroup()
                        .add(jPanelEmbaucherLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel10)
                            .add(jLabel7)
                            .add(jPanelEmbaucherLayout.createSequentialGroup()
                                .add(113, 113, 113)
                                .add(jPanelEmbaucherLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(jTextFieldPrenomEmbauche, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                    .add(jTextFieldNomEmbauche)))
                            .add(jLabel5))
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .add(jPanelEmbaucherLayout.createSequentialGroup()
                .add(152, 152, 152)
                .add(jLabel13)
                .add(0, 0, Short.MAX_VALUE))
        );
        jPanelEmbaucherLayout.setVerticalGroup(
            jPanelEmbaucherLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelEmbaucherLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel13)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 25, Short.MAX_VALUE)
                .add(jPanelEmbaucherLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelEmbaucherLayout.createSequentialGroup()
                        .add(jPanelEmbaucherLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanelEmbaucherLayout.createSequentialGroup()
                                .add(32, 32, 32)
                                .add(jPanelEmbaucherLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(jLabel7)
                                    .add(jTextFieldNomEmbauche, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(jPanelEmbaucherLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(jButton3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(jLabel31)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanelEmbaucherLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jTextFieldPrenomEmbauche, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel8))
                        .add(18, 18, 18)
                        .add(jSeparator4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel30))
                .add(21, 21, 21)
                .add(jPanelEmbaucherLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel10)
                    .add(jTextFieldAdresseRueEmbauche, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextFieldAdresseCpEmbauche, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextFieldAdresseVilleEmbauche, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanelEmbaucherLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel9)
                    .add(jTextFieldNumTelPersoEmbauche, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2)
                    .add(jTextFieldNumTelProEmbauche, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3))
                .add(18, 18, 18)
                .add(jPanelEmbaucherLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel12)
                    .add(jTextFieldEmailEmbauche, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelEmbaucherLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanelEmbaucherLayout.createSequentialGroup()
                        .add(jSeparator5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanelEmbaucherLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jPanelEmbaucherLayout.createSequentialGroup()
                                .add(jTextFieldIdEmbauche, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jTextFieldMDPEmbauche, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(35, 35, 35))
                    .add(jPanelEmbaucherLayout.createSequentialGroup()
                        .add(jLabel32)
                        .add(18, 18, 18)
                        .add(jLabel4)
                        .add(15, 15, 15)
                        .add(jLabel5)
                        .addContainerGap(43, Short.MAX_VALUE))))
        );

        jTabbedMenuDirecteur.addTab("Embaucher", jPanelEmbaucher);

        jButtonProm.setText("Promouvoir/Rétrograder");
        jButtonProm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPromActionPerformed(evt);
            }
        });

        jButton4.setText("Annuler");

        jScrollPane1.setViewportView(jListEmploye);

        jLabel15.setText("Promotion ou rétrogradation");

        jLabel24.setText("Statut Actuel :");

        jLabel25.setText("Nom de l'employé");

        jLabel26.setText("Prénom de l'employé");

        jButton7.setText("Voir infos");

        jLabel27.setText("Statut perdu :");

        jLabel28.setText("                ");

        jLabel29.setText("             ");

        org.jdesktop.layout.GroupLayout jPanelPromouvoirLayout = new org.jdesktop.layout.GroupLayout(jPanelPromouvoir);
        jPanelPromouvoir.setLayout(jPanelPromouvoirLayout);
        jPanelPromouvoirLayout.setHorizontalGroup(
            jPanelPromouvoirLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelPromouvoirLayout.createSequentialGroup()
                .add(274, 274, 274)
                .add(jLabel15)
                .add(0, 0, Short.MAX_VALUE))
            .add(jPanelPromouvoirLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelPromouvoirLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jButton4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 115, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanelPromouvoirLayout.createSequentialGroup()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 199, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jPanelPromouvoirLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanelPromouvoirLayout.createSequentialGroup()
                                .add(37, 37, 37)
                                .add(jPanelPromouvoirLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel25)
                                    .add(jTextFieldNomProm, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jLabel26)
                                    .add(jTextFieldPrenomProm, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(jPanelPromouvoirLayout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanelPromouvoirLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(jLabel24)
                                    .add(jLabel27))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanelPromouvoirLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel28)
                                    .add(jLabel29)))))
                    .add(jPanelPromouvoirLayout.createSequentialGroup()
                        .add(jButton7)
                        .add(127, 127, 127)
                        .add(jButtonProm, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 255, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPromouvoirLayout.setVerticalGroup(
            jPanelPromouvoirLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelPromouvoirLayout.createSequentialGroup()
                .add(30, 30, 30)
                .add(jLabel15)
                .add(4, 4, 4)
                .add(jPanelPromouvoirLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelPromouvoirLayout.createSequentialGroup()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 188, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelPromouvoirLayout.createSequentialGroup()
                        .add(jLabel25)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jTextFieldNomProm, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(1, 1, 1)
                        .add(jLabel26)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jTextFieldPrenomProm, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(65, 65, 65)
                        .add(jPanelPromouvoirLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel27)
                            .add(jLabel28))
                        .add(34, 34, 34)))
                .add(jPanelPromouvoirLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jButton7)
                    .add(jPanelPromouvoirLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel24)
                        .add(jLabel29)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 53, Short.MAX_VALUE)
                .add(jPanelPromouvoirLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButtonProm, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 54, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18))
        );

        jTabbedMenuDirecteur.addTab("Promouvoir/Rétrograder", jPanelPromouvoir);

        desktopPane.add(jTabbedMenuDirecteur);
        jTabbedMenuDirecteur.setBounds(0, 0, 550, 430);

        jButton1.setText("jButton1");

        jLabel6.setText("Modification de role d'un employé");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList1);

        jLabel11.setText("jLabel11");

        jLabel33.setText("jLabel33");

        jLabel34.setText("Nom de l'employé");

        jLabel35.setText("Prenom de l'employé");

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        org.jdesktop.layout.GroupLayout jPanelMenuResponsableLayout = new org.jdesktop.layout.GroupLayout(jPanelMenuResponsable);
        jPanelMenuResponsable.setLayout(jPanelMenuResponsableLayout);
        jPanelMenuResponsableLayout.setHorizontalGroup(
            jPanelMenuResponsableLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelMenuResponsableLayout.createSequentialGroup()
                .add(jPanelMenuResponsableLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelMenuResponsableLayout.createSequentialGroup()
                        .add(28, 28, 28)
                        .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 195, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jPanelMenuResponsableLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jLabel11)
                            .add(jLabel33)
                            .add(jLabel34)
                            .add(jLabel35)
                            .add(jTextField1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .add(jTextField2)))
                    .add(jPanelMenuResponsableLayout.createSequentialGroup()
                        .add(191, 191, 191)
                        .add(jLabel6)))
                .addContainerGap(184, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelMenuResponsableLayout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 137, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(30, 30, 30))
        );
        jPanelMenuResponsableLayout.setVerticalGroup(
            jPanelMenuResponsableLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelMenuResponsableLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel6)
                .add(jPanelMenuResponsableLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(jPanelMenuResponsableLayout.createSequentialGroup()
                        .add(33, 33, 33)
                        .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 187, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanelMenuResponsableLayout.createSequentialGroup()
                        .add(43, 43, 43)
                        .add(jLabel34)
                        .add(4, 4, 4)
                        .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel35)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jLabel33)
                        .add(18, 18, 18)
                        .add(jLabel11)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 130, Short.MAX_VALUE)
                .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        desktopPane.add(jPanelMenuResponsable);
        jPanelMenuResponsable.setBounds(0, 0, 550, 430);

        jButtonConnexion.setText("Connexion");
        jButtonConnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConnexionActionPerformed(evt);
            }
        });

        jButtonInscription.setText("Inscription");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bienvenue");

        org.jdesktop.layout.GroupLayout jPanelMenuAccueilLayout = new org.jdesktop.layout.GroupLayout(jPanelMenuAccueil);
        jPanelMenuAccueil.setLayout(jPanelMenuAccueilLayout);
        jPanelMenuAccueilLayout.setHorizontalGroup(
            jPanelMenuAccueilLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jSeparator1)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jSeparator2)
            .add(jPanelMenuAccueilLayout.createSequentialGroup()
                .add(219, 219, 219)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 133, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(198, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelMenuAccueilLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanelMenuAccueilLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelMenuAccueilLayout.createSequentialGroup()
                        .add(jButtonConnexion)
                        .add(245, 245, 245))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelMenuAccueilLayout.createSequentialGroup()
                        .add(jButtonInscription)
                        .add(244, 244, 244))))
        );
        jPanelMenuAccueilLayout.setVerticalGroup(
            jPanelMenuAccueilLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelMenuAccueilLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 53, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(44, 44, 44)
                .add(jButtonConnexion)
                .add(52, 52, 52)
                .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(37, 37, 37)
                .add(jButtonInscription)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        desktopPane.add(jPanelMenuAccueil);
        jPanelMenuAccueil.setBounds(0, -3, 550, 430);

        jLabel16.setText("jLabelRoleActu");

        jLabel14.setText("Statut");

        jLabel17.setText("Adresse");

        jLabel18.setText("Telephone");

        jLabel19.setText("E mail");

        jLabel20.setText("jLabel20");

        jLabel21.setText("jLabel21");

        jLabel22.setText("jLabel22");

        jLabel23.setText("jLabel23");

        jTextField3.setEditable(false);
        jTextField3.setText("jTextField3");

        jTextField4.setEditable(false);
        jTextField4.setText("jTextField4");

        jTextField5.setEditable(false);
        jTextField5.setText("jTextField5");

        jTextField6.setEditable(false);
        jTextField6.setText("jTextField6");

        jTextField7.setText("jTextField7");

        jTextField8.setText("jTextField8");

        jTextField9.setText("jTextField9");

        jButton5.setText("jButton5");

        jButton6.setText("jButton6");

        jButton12.setText("jButton12");

        jButtonModif.setText("Validé");

        jButton14.setText("jButton14");

        jButton15.setText("jButton15");

        jTextField10.setEditable(false);
        jTextField10.setText("jTextField10");

        jTextField11.setEditable(false);
        jTextField11.setText("jTextField11");

        org.jdesktop.layout.GroupLayout jPanelMenuEmployeLayout = new org.jdesktop.layout.GroupLayout(jPanelMenuEmploye);
        jPanelMenuEmploye.setLayout(jPanelMenuEmployeLayout);
        jPanelMenuEmployeLayout.setHorizontalGroup(
            jPanelMenuEmployeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelMenuEmployeLayout.createSequentialGroup()
                .add(jPanelMenuEmployeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanelMenuEmployeLayout.createSequentialGroup()
                        .add(44, 44, 44)
                        .add(jPanelMenuEmployeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel14)
                            .add(jLabel16)
                            .add(jSeparator3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 575, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jPanelMenuEmployeLayout.createSequentialGroup()
                        .add(46, 46, 46)
                        .add(jPanelMenuEmployeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel22)
                            .add(jLabel23))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanelMenuEmployeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanelMenuEmployeLayout.createSequentialGroup()
                                .add(jTextField8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(54, 54, 54)
                                .add(jButton5))
                            .add(jPanelMenuEmployeLayout.createSequentialGroup()
                                .add(jPanelMenuEmployeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(jPanelMenuEmployeLayout.createSequentialGroup()
                                        .add(jTextField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 138, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(69, 69, 69)
                                        .add(jTextField10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(106, 106, 106)
                                        .add(jTextField11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(jPanelMenuEmployeLayout.createSequentialGroup()
                                        .add(jPanelMenuEmployeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                            .add(jPanelMenuEmployeLayout.createSequentialGroup()
                                                .add(jTextField7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .add(148, 148, 148))
                                            .add(jPanelMenuEmployeLayout.createSequentialGroup()
                                                .add(jTextField9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .add(62, 62, 62)
                                                .add(jButton6)))
                                        .add(jPanelMenuEmployeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jPanelMenuEmployeLayout.createSequentialGroup()
                                                .add(19, 19, 19)
                                                .add(jPanelMenuEmployeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                    .add(jPanelMenuEmployeLayout.createSequentialGroup()
                                                        .add(13, 13, 13)
                                                        .add(jLabel17))
                                                    .add(jPanelMenuEmployeLayout.createSequentialGroup()
                                                        .add(1, 1, 1)
                                                        .add(jPanelMenuEmployeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                                            .add(jLabel19)
                                                            .add(jLabel18)))))
                                            .add(jPanelMenuEmployeLayout.createSequentialGroup()
                                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                                .add(jTextField6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 234, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                                    .add(jPanelMenuEmployeLayout.createSequentialGroup()
                                        .add(63, 63, 63)
                                        .add(jLabel20)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(jTextField4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .add(jLabel21)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jTextField5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .add(42, 42, 42)))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 116, Short.MAX_VALUE)
                                .add(jPanelMenuEmployeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                    .add(jButton12)
                                    .add(jButton14)
                                    .add(jButton15))
                                .add(10, 10, 10)))))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelMenuEmployeLayout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(jButtonModif, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 151, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(23, 23, 23))
        );
        jPanelMenuEmployeLayout.setVerticalGroup(
            jPanelMenuEmployeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelMenuEmployeLayout.createSequentialGroup()
                .add(16, 16, 16)
                .add(jLabel14)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jSeparator3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jLabel16)
                .add(13, 13, 13)
                .add(jLabel17)
                .add(4, 4, 4)
                .add(jPanelMenuEmployeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton14)
                    .add(jTextField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextField11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextField10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel18)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanelMenuEmployeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextField5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextField4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton12)
                    .add(jLabel20)
                    .add(jLabel21))
                .add(jPanelMenuEmployeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanelMenuEmployeLayout.createSequentialGroup()
                        .add(32, 32, 32)
                        .add(jTextField7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanelMenuEmployeLayout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jLabel19)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanelMenuEmployeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jTextField6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jButton15))))
                .add(18, 18, 18)
                .add(jPanelMenuEmployeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel22)
                    .add(jTextField8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton5))
                .add(18, 18, 18)
                .add(jPanelMenuEmployeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel23)
                    .add(jTextField9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton6))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jButtonModif, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .add(26, 26, 26))
        );

        desktopPane.add(jPanelMenuEmploye);
        jPanelMenuEmploye.setBounds(80, 10, 680, 420);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Accueil");

        connexionMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        connexionMenuItem.setMnemonic('o');
        connexionMenuItem.setText("Connexion");
        connexionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connexionMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(connexionMenuItem);

        deconnexionMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        deconnexionMenuItem.setMnemonic('s');
        deconnexionMenuItem.setText("Déconnexion");
        deconnexionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deconnexionMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(deconnexionMenuItem);

        SortieMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        SortieMenuItem.setMnemonic('x');
        SortieMenuItem.setText("Sortie");
        SortieMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortieMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(SortieMenuItem);

        nomMenuBar.add(fileMenu);

        aideMenu.setMnemonic('h');
        aideMenu.setText("Aide");

        aproposMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        aproposMenuItem.setMnemonic('c');
        aproposMenuItem.setText("A propos");
        aideMenu.add(aproposMenuItem);

        nomMenuBar.add(aideMenu);
        nomMenuBar.add(nomjMenu);

        setJMenuBar(nomMenuBar);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(desktopPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(desktopPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SortieMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortieMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SortieMenuItemActionPerformed

    private void connexionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connexionMenuItemActionPerformed
        // TODO add your handling code here:

        /**
         * création de la fenetre de connexion et attachement de cette dernière
         * à l'interface maj de connecte en retour
         */
        this.fenConnexion = new Connexion(this, true);
        this.fenConnexion.setVisible(true);

        //JOptionPane.showMessageDialog(this, "cc");
    }//GEN-LAST:event_connexionMenuItemActionPerformed

    private void deconnexionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deconnexionMenuItemActionPerformed
        // TODO add your handling code here:
        fenDeconnexion = new Deconnexion(this, true);
        this.fenDeconnexion.setVisible(true);
    }//GEN-LAST:event_deconnexionMenuItemActionPerformed


    private void jButtonPromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPromActionPerformed
        //recupere un employé et on peux le promouvoir 
        java.sql.Connection ct = SdzConnection.getInstance();
        String requete = null;
        String nom = jTextFieldNomProm.getText();
        String prenom = jTextFieldPrenomProm.getText();
        try {
            Statement state = ct.createStatement();
            System.out.println("select * from utilisateurs  WHERE nom = '" + nom + "'And prenom ='" + prenom +"'");
            ResultSet ligneRetournees = state.executeQuery("select * from utilisateurs  WHERE nom = '" + nom + "'And prenom ='" + prenom +"'");
            if (ligneRetournees.next()){
                    Integer idGrade = ligneRetournees.getInt("idGrade");
                    if (idGrade == 3){
                        requete = "UPDATE Utilisateurs SET idGrade=2 WHERE nom = '" + nom + "'And prenom ='" + prenom +"'";
                        jLabel28.setText(nom +" "+ prenom + "était Employé.");
                        jLabel29.setText(nom +" "+ prenom + " a été promu Responsable.");
                    } else {
                       if (idGrade == 2){
                        requete = "UPDATE Utilisateurs SET idGrade=3 WHERE nom = '" + nom + "'And prenom ='" + prenom +"'";
                        jLabel28.setText(nom +" "+ prenom + " était Responsable.");
                        jLabel29.setText(nom +" "+ prenom + " a été rétrograder Employé.");
                    }
                    }
            }
              
            state.executeUpdate(requete);
        } catch (SQLException ex) {
            Logger.getLogger(InterfaceGraphique.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButtonPromActionPerformed

    private void jButtonConnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConnexionActionPerformed
        this.fenConnexion = new Connexion(this, true);
        this.fenConnexion.setVisible(true);
    }//GEN-LAST:event_jButtonConnexionActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (jTextFieldNomEmbauche.getText().length() == 0 || jTextFieldPrenomEmbauche.getText().length() == 0 || jTextFieldAdresseRueEmbauche.getText().length() == 0 || jTextFieldAdresseCpEmbauche.getText().length() == 0 || jTextFieldAdresseVilleEmbauche.getText().length() == 0 || jTextFieldNumTelPersoEmbauche.getText().length() == 0 || jTextFieldNumTelProEmbauche.getText().length() == 0 || jTextFieldEmailEmbauche.getText().length() == 0 || jTextFieldIdEmbauche.getText().length() == 0 || jTextFieldMDPEmbauche.getText().length() == 0) {
            JOptionPane.showInternalMessageDialog(this, "Erreur");
        } else {

            java.sql.Connection ct = SdzConnection.getInstance();
            try {
                Statement requete = ct.createStatement();
                String nom = jTextFieldNomEmbauche.getText();
                String prenom = jTextFieldPrenomEmbauche.getText();
                String adresseRue = jTextFieldAdresseRueEmbauche.getText();
                String adresseCp = jTextFieldAdresseCpEmbauche.getText();
                String adresseVille = jTextFieldAdresseVilleEmbauche.getText();
                String numTelPerso = jTextFieldNumTelPersoEmbauche.getText();
                String numTelPro = jTextFieldNumTelProEmbauche.getText();
                String email = jTextFieldEmailEmbauche.getText();
                String id = jTextFieldIdEmbauche.getText();
                String mdp = jTextFieldMDPEmbauche.getText();
                Integer grade = 3;
                Integer role = 3;
//            Integer grade = jComboBoxGrade.getSelectedIndex() + 1;
//           Integer role = jComboBoxRole.getSelectedIndex() + 1;
                Integer lignesRetournees = requete.executeUpdate("INSERT INTO Utilisateurs(nom,prenom,adresse_rue,adresse_cp,adresse_ville,tel_personnel,tel_professionnel,mail,identifiant,mot_de_passe,idRoles,idGrade) VALUES ('" + nom + "','" + prenom + "','" + adresseRue + "','" + adresseCp + "','" + adresseVille + "','" + numTelPerso + "','" + numTelPro + "','" + email + "','" + id + "','" + mdp + "','" + grade + "','" + role + "')");
            } catch (SQLException ex) {
                Logger.getLogger(InterfaceGraphique.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jTextFieldNomEmbauche.setText("");
        jTextFieldPrenomEmbauche.setText("");
        jTextFieldAdresseRueEmbauche.setText("");
        jTextFieldAdresseCpEmbauche.setText("");
        jTextFieldAdresseVilleEmbauche.setText("");
        jTextFieldNumTelPersoEmbauche.setText("");
        jTextFieldNumTelProEmbauche.setText("");
        jTextFieldEmailEmbauche.setText("");
        jTextFieldIdEmbauche.setText("");
        jTextFieldMDPEmbauche.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed
    public void connecte(String leNom, String lePrenom, String leGrade, String leRole) throws SQLException {
        //maj de l'etat de la connexion
        this.connecte = true;
        //ajout du nom,prenom, et role dans la fenetre si directeur
        if (leGrade.equals("Directeur")) {
            this.nomjMenu.setText("Bonjour M. " + leNom +" / Role : " + leRole);
        } else {
                    //ajout du nom,prenom,dans la fenetre si emplyé ou responsable

            this.nomjMenu.setText("Connecté en tant que : " + leNom + " " + lePrenom);
        }

        //accueil devient leGrade de l'utilisateur
        this.fileMenu.setText(leGrade);
        this.nomjMenu.setEnabled(false);
        jPanelMenuAccueil.setVisible(!connecte);
        if (leGrade.equals("Directeur")) {
            jTabbedMenuDirecteur.setVisible(true);
//            java.sql.Connection ct = SdzConnection.getInstance();
//            Statement requete = ct.createStatement();
//            ResultSet lignesRetournees = requete.executeQuery("select * from Utilisateurs");
//            while(lignesRetournees.next()){
//                jListEmploye.add(leNom);
//            }
        }
        if (leGrade.equals("Responsable")) {
            jPanelMenuResponsable.setVisible(true);
        }
        if (leGrade.equals("Employé")) {
            jPanelMenuEmploye.setVisible(true);
            this.jLabel16.setText("Vous étes actuelement " + leRole + " dans l'entreprise");
        }

    }

    public void deconnecte() {
        this.connecte = false;
        this.nomjMenu.setText(null);
        this.fileMenu.setText("Acceuil");
        jPanelMenuAccueil.setVisible(!connecte);
        jTabbedMenuDirecteur.setVisible(connecte);
        jPanelMenuEmploye.setVisible(connecte);
        
    }

    public void majConnexion() {
        deconnexionMenuItem.setEnabled(this.connecte);
        connexionMenuItem.setEnabled(!this.connecte);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceGraphique().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem SortieMenuItem;
    private javax.swing.JMenu aideMenu;
    private javax.swing.JMenuItem aproposMenuItem;
    private javax.swing.JMenuItem connexionMenuItem;
    private javax.swing.JMenuItem deconnexionMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButtonConnexion;
    private javax.swing.JButton jButtonInscription;
    private javax.swing.JButton jButtonModif;
    private javax.swing.JButton jButtonProm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jListEmploye;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanelEmbaucher;
    private javax.swing.JPanel jPanelMenuAccueil;
    private javax.swing.JPanel jPanelMenuEmploye;
    private javax.swing.JPanel jPanelMenuResponsable;
    private javax.swing.JPanel jPanelPromouvoir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTabbedPane jTabbedMenuDirecteur;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jTextFieldAdresseCpEmbauche;
    private javax.swing.JTextField jTextFieldAdresseRueEmbauche;
    private javax.swing.JTextField jTextFieldAdresseVilleEmbauche;
    private javax.swing.JTextField jTextFieldEmailEmbauche;
    private javax.swing.JTextField jTextFieldIdEmbauche;
    private javax.swing.JTextField jTextFieldMDPEmbauche;
    private javax.swing.JTextField jTextFieldNomEmbauche;
    private javax.swing.JTextField jTextFieldNomProm;
    private javax.swing.JTextField jTextFieldNumTelPersoEmbauche;
    private javax.swing.JTextField jTextFieldNumTelProEmbauche;
    private javax.swing.JTextField jTextFieldPrenomEmbauche;
    private javax.swing.JTextField jTextFieldPrenomProm;
    private javax.swing.JMenuBar nomMenuBar;
    private javax.swing.JMenu nomjMenu;
    // End of variables declaration//GEN-END:variables
}
