/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package appli_pro;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.swing.JOptionPane;

/**
 *
 * @author nc
 */
public class InterfaceGraphique extends javax.swing.JFrame {

    /**
     * attribut qui indique si l'etudiant est connecté ou non
     */
    private boolean connecte;
    private Etudiants infoEtudiant;

    /**
     * interface graphique
     */
    private Connexion fenConnexion;
    private Deconnexion fenDeconnexion;
    private Inscription fenInscription;
    private Accueil_responsable fenResponsable;
    private Promouvoir fenPromouvoir;
    private Retrograder fenRetrograder;
    private Personnelles fenPersonnelles;
    private GererFormation fenFormation;
    private PersonnellesDirecteur fenPersonnellesDirecteur;
    private PersonnellesResponsable fenPersonnellesResponsable;
    private FormationsDirecteur fenFormationsDirecteur;
    private FormationsResponsable fenFormationsResponsable;
    private ConsulterPositionEmploye fenConsulterPositionEmploye;
    private ConsulterPositionResponsable fenConsulterResponsable;
    private ConsulterPositionDirecteur fenConsulterDirecteur;

    /**
     * constructeur : Creates new form InterfaceGraphique
     *
     */
    public InterfaceGraphique() {
        initComponents();
        //par defaut, la connexion est inactive
        this.connecte = false;
        //element du menu de deconnexion grisé
        this.majConnexion();

        //centrage
        this.setLocationRelativeTo(null);
        //titre 
        this.setTitle("Gestion des étudiants du bts sio");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jFileChooser1 = new javax.swing.JFileChooser();
        jResponsable = new javax.swing.JButton();
        desktopPane = new javax.swing.JDesktopPane();
        jAccueil = new javax.swing.JPanel();
        jConnexion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSortie2 = new javax.swing.JButton();
        jDirecteur = new javax.swing.JPanel();
        jInscription = new javax.swing.JButton();
        jSortie1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jDeconnexionDirecteur = new javax.swing.JButton();
        jPromouvoirEmployee = new javax.swing.JButton();
        jRetrogarder = new javax.swing.JButton();
        jModifications1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanelResponsable = new javax.swing.JPanel();
        jChangement = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jSortie3 = new javax.swing.JButton();
        jDeconnexionResponsable = new javax.swing.JButton();
        jModifications2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jEmploye = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jModifications = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        nomMenuBar = new javax.swing.JMenuBar();
        aideMenu = new javax.swing.JMenu();
        aproposMenuItem = new javax.swing.JMenuItem();
        nomjMenu = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        deconnexionMenuItem = new javax.swing.JMenuItem();
        SortieMenuItem = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jResponsable.setText("Responsable");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(0, 153, 153));
        desktopPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        desktopPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jAccueil.setBackground(new java.awt.Color(102, 102, 102));
        jAccueil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jAccueil.setMaximumSize(new java.awt.Dimension(3210, 32767));

        jConnexion.setText("Connexion");
        jConnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConnexionActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Accueil");

        jSortie2.setText("Sortie");
        jSortie2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSortie2ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jAccueilLayout = new org.jdesktop.layout.GroupLayout(jAccueil);
        jAccueil.setLayout(jAccueilLayout);
        jAccueilLayout.setHorizontalGroup(
            jAccueilLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jAccueilLayout.createSequentialGroup()
                .add(894, 894, 894)
                .add(jAccueilLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 123, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jAccueilLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jConnexion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 110, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jSortie2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 110, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(988, Short.MAX_VALUE))
        );
        jAccueilLayout.setVerticalGroup(
            jAccueilLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jAccueilLayout.createSequentialGroup()
                .add(48, 48, 48)
                .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(100, 100, 100)
                .add(jConnexion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(110, 110, 110)
                .add(jSortie2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(645, Short.MAX_VALUE))
        );

        desktopPane.add(jAccueil);
        jAccueil.setBounds(0, 0, 2007, 1035);

        jDirecteur.setBackground(new java.awt.Color(102, 102, 102));

        jInscription.setText("Créer un Employé(e)");
        jInscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInscriptionActionPerformed(evt);
            }
        });

        jSortie1.setText("Sortie");
        jSortie1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSortie1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Accueil Directeur");
        jLabel1.setToolTipText("");

        jDeconnexionDirecteur.setText("Déconnexion");
        jDeconnexionDirecteur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeconnexionDirecteurActionPerformed(evt);
            }
        });

        jPromouvoirEmployee.setText("Promouvoir un Employé(e)");
        jPromouvoirEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPromouvoirEmployeeActionPerformed(evt);
            }
        });

        jRetrogarder.setText("Rétrograder Employé(e)");
        jRetrogarder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRetrogarderActionPerformed(evt);
            }
        });

        jModifications1.setText("Gérer Modifications Personnelles");
        jModifications1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jModifications1ActionPerformed(evt);
            }
        });

        jButton3.setText("Gérer les formations");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton7.setText("Consulter Sa Position");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jDirecteurLayout = new org.jdesktop.layout.GroupLayout(jDirecteur);
        jDirecteur.setLayout(jDirecteurLayout);
        jDirecteurLayout.setHorizontalGroup(
            jDirecteurLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDirecteurLayout.createSequentialGroup()
                .addContainerGap(1014, Short.MAX_VALUE)
                .add(jDirecteurLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jDirecteurLayout.createSequentialGroup()
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 381, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(585, 585, 585))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jDirecteurLayout.createSequentialGroup()
                        .add(jPromouvoirEmployee)
                        .add(718, 718, 718))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jDirecteurLayout.createSequentialGroup()
                        .add(jRetrogarder)
                        .add(728, 728, 728))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jDirecteurLayout.createSequentialGroup()
                        .add(jDirecteurLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jButton3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 187, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jModifications1))
                        .add(700, 700, 700))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jDirecteurLayout.createSequentialGroup()
                        .add(jButton7)
                        .add(724, 724, 724))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jDirecteurLayout.createSequentialGroup()
                        .add(jDirecteurLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jSortie1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 110, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jDeconnexionDirecteur, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 103, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(732, 732, 732))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jDirecteurLayout.createSequentialGroup()
                        .add(jInscription)
                        .add(729, 729, 729))))
        );
        jDirecteurLayout.setVerticalGroup(
            jDirecteurLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jDirecteurLayout.createSequentialGroup()
                .add(29, 29, 29)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 100, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(40, 40, 40)
                .add(jInscription, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(37, 37, 37)
                .add(jPromouvoirEmployee)
                .add(38, 38, 38)
                .add(jRetrogarder)
                .add(45, 45, 45)
                .add(jModifications1)
                .add(52, 52, 52)
                .add(jButton7)
                .add(32, 32, 32)
                .add(jButton3)
                .add(32, 32, 32)
                .add(jDeconnexionDirecteur, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(29, 29, 29)
                .add(jSortie1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(457, Short.MAX_VALUE))
        );

        desktopPane.add(jDirecteur);
        jDirecteur.setBounds(0, 0, 1980, 1110);

        jPanelResponsable.setBackground(new java.awt.Color(102, 102, 102));

        jChangement.setText("Changement Position Employée");
        jChangement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChangementActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Accueil Responsable");

        jSortie3.setText("Sortie");
        jSortie3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSortie3ActionPerformed(evt);
            }
        });

        jDeconnexionResponsable.setText("Déconnexion");
        jDeconnexionResponsable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDeconnexionResponsableActionPerformed(evt);
            }
        });

        jModifications2.setText("Gérer Modifications Personnelles");
        jModifications2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jModifications2ActionPerformed(evt);
            }
        });

        jButton4.setText("Gèrer les formations");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setText("Consulter Sa Position");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanelResponsableLayout = new org.jdesktop.layout.GroupLayout(jPanelResponsable);
        jPanelResponsable.setLayout(jPanelResponsableLayout);
        jPanelResponsableLayout.setHorizontalGroup(
            jPanelResponsableLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelResponsableLayout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(jPanelResponsableLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelResponsableLayout.createSequentialGroup()
                        .add(jLabel3)
                        .add(715, 715, 715))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelResponsableLayout.createSequentialGroup()
                        .add(jPanelResponsableLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jChangement)
                            .add(jModifications2)
                            .add(jButton4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 187, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(789, 789, 789))))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelResponsableLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jButton6)
                .add(818, 818, 818))
            .add(jPanelResponsableLayout.createSequentialGroup()
                .add(1047, 1047, 1047)
                .add(jPanelResponsableLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jSortie3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 110, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jDeconnexionResponsable, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 103, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(820, Short.MAX_VALUE))
        );
        jPanelResponsableLayout.setVerticalGroup(
            jPanelResponsableLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelResponsableLayout.createSequentialGroup()
                .add(39, 39, 39)
                .add(jLabel3)
                .add(78, 78, 78)
                .add(jModifications2)
                .add(74, 74, 74)
                .add(jChangement)
                .add(72, 72, 72)
                .add(jButton4)
                .add(74, 74, 74)
                .add(jButton6)
                .add(81, 81, 81)
                .add(jDeconnexionResponsable, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(77, 77, 77)
                .add(jSortie3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(321, Short.MAX_VALUE))
        );

        desktopPane.add(jPanelResponsable);
        jPanelResponsable.setBounds(0, 0, 1977, 1023);

        jEmploye.setBackground(new java.awt.Color(102, 102, 102));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Accueil Employé");

        jModifications.setText("Gérer Modifications Personnelles");
        jModifications.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jModificationsActionPerformed(evt);
            }
        });

        jButton1.setText("Sortie");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Gérer les formations");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setText("Consulter Sa Position");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jEmployeLayout = new org.jdesktop.layout.GroupLayout(jEmploye);
        jEmploye.setLayout(jEmployeLayout);
        jEmployeLayout.setHorizontalGroup(
            jEmployeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jEmployeLayout.createSequentialGroup()
                .add(jEmployeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jEmployeLayout.createSequentialGroup()
                        .add(914, 914, 914)
                        .add(jButton1))
                    .add(jEmployeLayout.createSequentialGroup()
                        .add(883, 883, 883)
                        .add(jButton5)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(jEmployeLayout.createSequentialGroup()
                .add(jEmployeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jEmployeLayout.createSequentialGroup()
                        .add(852, 852, 852)
                        .add(jEmployeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 187, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jModifications)))
                    .add(jEmployeLayout.createSequentialGroup()
                        .add(825, 825, 825)
                        .add(jLabel4)))
                .add(0, 1505, Short.MAX_VALUE))
        );
        jEmployeLayout.setVerticalGroup(
            jEmployeLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jEmployeLayout.createSequentialGroup()
                .add(34, 34, 34)
                .add(jLabel4)
                .add(77, 77, 77)
                .add(jModifications)
                .add(91, 91, 91)
                .add(jButton2)
                .add(67, 67, 67)
                .add(jButton5)
                .add(89, 89, 89)
                .add(jButton1)
                .addContainerGap(534, Short.MAX_VALUE))
        );

        desktopPane.add(jEmploye);
        jEmploye.setBounds(0, 0, 2587, 1028);

        getContentPane().add(desktopPane, java.awt.BorderLayout.CENTER);

        nomMenuBar.setPreferredSize(new java.awt.Dimension(35, 25));

        aideMenu.setMnemonic('h');
        aideMenu.setText("Aide");
        aideMenu.setMaximumSize(new java.awt.Dimension(33, 33));

        aproposMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        aproposMenuItem.setMnemonic('c');
        aproposMenuItem.setText("A propos");
        aideMenu.add(aproposMenuItem);

        nomMenuBar.add(aideMenu);
        nomMenuBar.add(nomjMenu);

        jMenu1.setText("Menu");

        deconnexionMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        deconnexionMenuItem.setMnemonic('s');
        deconnexionMenuItem.setText("Déconnexion");
        jMenu1.add(deconnexionMenuItem);

        SortieMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        SortieMenuItem.setMnemonic('x');
        SortieMenuItem.setText("Sortie");
        jMenu1.add(SortieMenuItem);

        nomMenuBar.add(jMenu1);

        setJMenuBar(nomMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jConnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConnexionActionPerformed
        // TODO add your handling code here:
        this.fenConnexion = new Connexion(this, true);
        this.fenConnexion.setVisible(true);
    }//GEN-LAST:event_jConnexionActionPerformed

    private void jSortie1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSortie1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jSortie1ActionPerformed

    private void jInscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInscriptionActionPerformed
        // TODO add your handling code here:
        this.fenInscription = new Inscription(this, true);
        this.fenInscription.setVisible(true);
    }//GEN-LAST:event_jInscriptionActionPerformed

    private void jSortie2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSortie2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jSortie2ActionPerformed

    private void jSortie3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSortie3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jSortie3ActionPerformed

    private void jChangementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChangementActionPerformed
        // TODO add your handling code here:
        this.fenResponsable = new Accueil_responsable(this, true);
        this.fenResponsable.setVisible(true);
    }//GEN-LAST:event_jChangementActionPerformed

    private void jDeconnexionDirecteurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeconnexionDirecteurActionPerformed
        // TODO add your handling code here:
        fenDeconnexion = new Deconnexion(this, true);
        this.fenDeconnexion.setVisible(true);
    }//GEN-LAST:event_jDeconnexionDirecteurActionPerformed

    private void jDeconnexionResponsableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeconnexionResponsableActionPerformed
        // TODO add your handling code here:
        fenDeconnexion = new Deconnexion(this, true);
        this.fenDeconnexion.setVisible(true);
    }//GEN-LAST:event_jDeconnexionResponsableActionPerformed

    private void jPromouvoirEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPromouvoirEmployeeActionPerformed
        // TODO add your handling code here:
        fenPromouvoir = new Promouvoir(this, true);
        this.fenPromouvoir.setVisible(true);
    }//GEN-LAST:event_jPromouvoirEmployeeActionPerformed

    private void jRetrogarderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRetrogarderActionPerformed
        // TODO add your handling code here:
        fenRetrograder = new Retrograder(this, true);
        this.fenRetrograder.setVisible(true);
    }//GEN-LAST:event_jRetrogarderActionPerformed

    private void jModificationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jModificationsActionPerformed
        // TODO add your handling code here:
        fenPersonnelles = new Personnelles(this, true);
        this.fenPersonnelles.setVisible(true);
    }//GEN-LAST:event_jModificationsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        fenFormation = new GererFormation(this, true);
        this.fenFormation.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jModifications1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jModifications1ActionPerformed
        // TODO add your handling code here: 
        fenPersonnellesDirecteur = new PersonnellesDirecteur(this, true);
        this.fenPersonnellesDirecteur.setVisible(true);
    }//GEN-LAST:event_jModifications1ActionPerformed

    private void jModifications2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jModifications2ActionPerformed
        // TODO add your handling code here:
        fenPersonnellesResponsable = new PersonnellesResponsable(this, true);
        this.fenPersonnellesResponsable.setVisible(true);
    }//GEN-LAST:event_jModifications2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        fenFormationsDirecteur = new FormationsDirecteur(this, true);
        this.fenFormationsDirecteur.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        fenFormationsResponsable = new FormationsResponsable(this, true);
        this.fenFormationsResponsable.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        fenConsulterPositionEmploye = new ConsulterPositionEmploye(this, true);
        this.fenConsulterPositionEmploye.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        fenConsulterResponsable = new ConsulterPositionResponsable(this, true);
        this.fenConsulterResponsable.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        fenConsulterDirecteur = new ConsulterPositionDirecteur(this, true);
        this.fenConsulterDirecteur.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed
    public void connecte(String leNom) {
        //maj de l'etat de la connexion

        this.connecte = true;
        //ajout du nom dans la fenetre
        this.nomjMenu.setText("Connecté en tant que : " + leNom);

        this.nomjMenu.setEnabled(false);

    }

    public void deconnecte() {
        this.connecte = false;
        this.nomjMenu.setText(null);
    }

    public void majConnexion() {

        deconnexionMenuItem.setEnabled(this.connecte);
        nomjMenu.setVisible(true);
        jResponsable.setEnabled(false);
        jDirecteur.setVisible(false);
        jPanelResponsable.setVisible(false);
        jEmploye.setVisible(false);
        jAccueil.setVisible(true);

    }

    public void roles() {
        jAccueil.setVisible(false);
        nomjMenu.setVisible(true);
        jDirecteur.setVisible(true);

    }

    public void responsablee() {
        jAccueil.setVisible(false);
        nomjMenu.setVisible(true);
        jPanelResponsable.setVisible(true);
    }

    public void personnels() {
        jAccueil.setVisible(false);
        jEmploye.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceGraphique().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem SortieMenuItem;
    private javax.swing.JMenu aideMenu;
    private javax.swing.JMenuItem aproposMenuItem;
    private javax.swing.JMenuItem deconnexionMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JPanel jAccueil;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jChangement;
    private javax.swing.JButton jConnexion;
    private javax.swing.JButton jDeconnexionDirecteur;
    private javax.swing.JButton jDeconnexionResponsable;
    private javax.swing.JPanel jDirecteur;
    private javax.swing.JPanel jEmploye;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JButton jInscription;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JButton jModifications;
    private javax.swing.JButton jModifications1;
    private javax.swing.JButton jModifications2;
    private javax.swing.JPanel jPanelResponsable;
    private javax.swing.JButton jPromouvoirEmployee;
    private javax.swing.JButton jResponsable;
    private javax.swing.JButton jRetrogarder;
    private javax.swing.JButton jSortie1;
    private javax.swing.JButton jSortie2;
    private javax.swing.JButton jSortie3;
    private javax.swing.JMenuBar nomMenuBar;
    private javax.swing.JMenu nomjMenu;
    // End of variables declaration//GEN-END:variables
}
